"""
Django settings for SBAWebsite project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# Configuration de la base de données MSSQL
MSSQL_ENGINE = 'mssql'
MSSQL_NAME = os.getenv('databasedj_')  # Nom de la base de données
MSSQL_USER = os.getenv('usernamedj_')  # Nom d'utilisateur
MSSQL_PASSWORD = os.getenv('passworddj_')  # Mot de passe
MSSQL_HOST = os.getenv('serverdj_')  # Nom du serveur Azure SQL
MSSQL_PORT = os.getenv('portdj_')  # Port (1433 par défaut pour Azure SQL)


# Configuration de Django
SECRET_KEY = os.getenv('SECRET_KEY_')  # Clé secrète pour Django
DEBUG = os.getenv('DEBUG') == 'True'  # Mode debug (True ou False)
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')  # Liste des hôtes autorisés
FASTAPI_URL = os.getenv('API_URL')  # URL de l'API FastAPI


# Application definition

INSTALLED_APPS = [
    #My Apps
    "bankapp",
    "tailwind",
    "theme",
    "channels",
    "widget_tweaks",
    #"django_browser_reload",  

    #Base Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    #"django_browser_reload.middleware.BrowserReloadMiddleware",
    #"django_browser_reload.middleware.BrowserReloadMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SBAWebsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'bankapp/templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SBAWebsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sql_server',
        'NAME': 'ta_base_django',
        'USER': 'ton_utilisateur',
        'PASSWORD': 'ton_mot_de_passe',
        'HOST': 'tonserveur.database.windows.net',
        'PORT': '1433',
        'OPTIONS': {'driver': 'ODBC Driver 18 for SQL Server'},
    }
}"""

# Configuration de la base de données
DATABASES = {
    'default': {
        'ENGINE': MSSQL_ENGINE,
        'NAME': MSSQL_NAME,
        'USER': MSSQL_USER,
        'PASSWORD': MSSQL_PASSWORD,
        'HOST': MSSQL_HOST,
        'PORT': MSSQL_PORT,
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',  # Utiliser le driver ODBC 18 pour SQL Server
            'Encrypt': 'yes',  # Activer le chiffrement
            'TrustServerCertificate': 'no',  # Ne pas faire confiance au certificat du serveur
            'Connection Timeout': 30,  # Timeout de connexion
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#Model to use for authentification
AUTH_USER_MODEL = 'bankapp.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Redis Channel Layer Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # Redis server
        },
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# FAST API connexion
#FASTAPI_URL = "http://20.40.158.29:8000"  # Exemple d'URL, ajustez-la selon votre configuration