"""
Django settings for SBAWebsite project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# load_dotenv()
# print(50*"CHARGEMENT .ENV")  # Debug temporaire
# print(os.getenv('databasedj_'))  # Debug temporaire

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = BASE_DIR / ".env"

print(f"📌 Fichier .env trouvé ? {env_path.exists()}")
load_dotenv(env_path)
print(f"📌 databasedj: {os.getenv('databasedj')}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-%iyebyj1+lyr-%h0ktd#&yvsh4s+2kohiqn7!q9p-t+_dsq7-f"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Configuration de la base de données MSSQL
MSSQL_ENGINE = 'mssql'
MSSQL_NAME = os.getenv('databasedj')  # Nom de la base de données
MSSQL_USER = os.getenv('usernamedj')  # Nom d'utilisateur
MSSQL_PASSWORD = os.getenv('passworddj')  # Mot de passe
MSSQL_HOST = os.getenv('serverdj')  # Nom du serveur Azure SQL
MSSQL_PORT = os.getenv('portdj')  # Port (1433 par défaut pour Azure SQL)
# DATABASE_URL = os.getenv('DATABASE_URL')  # 



# Configuration de Django
SECRET_KEY = os.getenv('SECRET_KEY')  # Clé secrète pour Django
DEBUG = os.getenv('DEBUG') == 'False'  # Mode debug (True ou False)
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')  # Liste des hôtes autorisés
FASTAPI_URL = os.getenv('API_URL')  # URL de l'API FastAPI

# Application definition

INSTALLED_APPS = [
    #My Apps
    "bankapp",
    "tailwind",
    "theme",
    "channels",
    "widget_tweaks",
    #"django_browser_reload",  

    #Base Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    #"django_browser_reload.middleware.BrowserReloadMiddleware",
    #"django_browser_reload.middleware.BrowserReloadMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SBAWebsite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'bankapp/templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SBAWebsite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#SQLite
# # DATABASES = {
# #     "default": {
# #         "ENGINE": "django.db.backends.sqlite3",
# #         "NAME": BASE_DIR / "db.sqlite3",
# #     }
# # }

DATABASES = {
    'default': {
        'ENGINE': MSSQL_ENGINE,
        'NAME': MSSQL_NAME,
        'USER': MSSQL_USER,
        'PASSWORD': MSSQL_PASSWORD,
        'HOST': MSSQL_HOST,
        'PORT': MSSQL_PORT,
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',  # Utiliser le driver ODBC 18 pour SQL Server
            'Encrypt': 'yes',  # Activer le chiffrement
            'TrustServerCertificate': 'no',  # Ne pas faire confiance au certificat du serveur
            'Connection Timeout': 30,  # Timeout de connexion
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#Model to use for authentification
AUTH_USER_MODEL = 'bankapp.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Redis Channel Layer Configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],  # Redis server
        },
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# FAST API connexion
FASTAPI_URL = "http://localhost:8001"  # Exemple d'URL, ajustez-la selon votre configuration
